[default]
APP_LABEL="Starter API"
 
[development]
APP_LABEL="Starter API DEV"

[ci]
APP_LABEL="Starter API CI"

[testing]
APP_LABEL="Starter API TEST"

[staging]
APP_LABEL="Starter API ST"

[production]
APP_LABEL="Starter API PR"