[default]
APP_NAME="Starter API"

[development]
APP_NAME="Starter API DEV"

[ci]
APP_NAME="Starter API CI"

[testing]
APP_NAME="Starter API TEST"

[staging]
APP_NAME="Starter API ST"

[production]
APP_NAME="Starter API PR"