version: '3.8'

services:
  api-test:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    # Using Debugpy
    command: [
      "bash", 
      "-c",
      "while !</dev/tcp/db/5432; do sleep 1; done; pytest tests"
    ]
    volumes:
      - ./backend:/usr/src/app/backend
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/starter_db_dev
      - ENV_FOR_DYNACONF=development
    depends_on:
      - db
  db:
    image: postgres:15.1-alpine
    env_file: .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=starter_db_dev

    expose:
      - 5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres_data:
