version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8004:8000
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./backend:/usr/src/app/backend
