version: '3.8'

services:
  web-test:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    # Using Debugpy
    env_file: .env
    command: [
      "bash", 
      "-c",
      "while !</dev/tcp/db/5432; do sleep 1; done; python -m debugpy --listen 0.0.0.0:5678 -m uvicorn backend.main:app --host 0.0.0.0 --reload"
    ]
    volumes:
      - ./backend:/usr/src/app/backend
    ports:
      - 8004:8000
      - 5678:5678
    depends_on:
      - db
  db:
    image: postgres:15.1-alpine
    env_file: .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=starter_db_dev

    expose:
      - 5432

