version: '3.8'

services:

  # test:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   command: [
  #     "bash", 
  #     "-c",
  #     "while !</dev/tcp/db/5432; do sleep 1; done; uvicorn backend.main:app --host 0.0.0.0 --reload"
  #   ]
  #   volumes:
  #     - ./backend:/usr/src/app/backend
  #   environment:
  #     - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/starter_db_dev
  #     - ENV_FOR_DYNACONF=testing
  #   ports:
  #     - 8005:8000
  #     # - 5678:5678
  #   depends_on:
  #     - db
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    # Using Debugpy
    command: [
      "bash", 
      "-c",
      "while !</dev/tcp/db/5432; do sleep 1; done; python -m debugpy --listen 0.0.0.0:5678 -m uvicorn backend.main:app --host 0.0.0.0 --reload"
    ]
    volumes:
      - ./backend:/usr/src/app/backend
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/starter_db_dev
      - ENV_FOR_DYNACONF=development
    ports:
      - 8004:8000
      - 5678:5678
    depends_on:
      - db
  db:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=starter_db_dev

    expose:
      - 5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres_data:
