# pull official base image
FROM python:3.11-slim

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies

RUN apt-get update &&  \
    apt-get install -y \
    netcat-traditional \
    curl \
    postgresql \
    gcc \
    python3-dev \
    libc6 \
    gnupg

# copy requirements file
COPY ./requirements.txt /usr/src/app/requirements.txt

RUN pip install -r /usr/src/app/requirements.txt

# copy project
COPY ./backend /usr/src/app/
